export type TypographyType =
  | 'Heading1'
  | 'Heading2'
  | 'Heading3'
  | 'Heading4'
  | 'Heading5'
  | 'Heading6'
  | 'Subtitle1'
  | 'Subtitle2'
  | 'Paragraph1'
  | 'Paragraph2'
  | 'Button'
  | 'Caption'
  | 'OverLine'
